spring:
  application:
    name: registeration-center
eureka:
  client:
    service-url:
      defaultZone: http://registration-center:8000/eureka/
    fetch-registry: false
    register-with-eureka: false
server:
  port: 8000

