spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///upms?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 50003

eureka:
  client:
    service-url:
      defaultZone: http://registration-center:8000/eureka/
