spring:
  application:
    name: configuration-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gaoyuyue/springcloud-ddd-sample/
          search-paths: config-repo
  rabbitmq:
    addresses: rabbitmq
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://registration-center:8000/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8001
management:
  endpoints:
    web:
      exposure:
        include: '*'