spring:
  application:
    name: zipkin-server
eureka:
  client:
    service-url:
      defaultZone: http://registration-center:8000/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8003
management:
  metrics:
    web:
      server:
        auto-time-requests: false
